version: "3.8"
services:
    r-web:
        container_name: r-web
        image: marclr199/r-web:1.0
        working_dir: /var/www/r-web
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/r-web
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - mysql_db

    mysql_db:
        container_name: mysql_db
        image: mysql:8.0.32
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - "3308:3306"

networks:
    default:
        external: true
        name: rweb
